version: '3.9'
services:
  app:
    build: .
    env_file: default.env
    depends_on:
      - postgres
    volumes:
      - ./src/dbcp:/app/dbcp:ro
      - ../pudl-work/sqlite/pudl.sqlite:/app/pudl.sqlite:ro
  postgres:
    image: postgis/postgis:13-3.1-alpine
    restart: unless-stopped
    env_file: default.env
    ports:
      - ${POSTGRES_PORT}:5432
