version: "3.8"
services:
  postgres:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=dbcp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data # this is the default, but make it explicit
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/docker_init_sql/:/docker-entrypoint-initdb.d # files execute in lex order

  postgres-test:
    # same as postgres but no persistence and different port
    image: postgis/postgis:13-3.1-alpine
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=dbcp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5430:5432"
    volumes:
      - ./sql/docker_init_sql/:/docker-entrypoint-initdb.d # files execute in lex order
      # no volume because we probalby don't need to persist test data

  pgadmin:
    image: dpage/pgadmin4:6.2
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@fake.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"
volumes:
  postgres-data: null
  pgadmin-data: null
