name: dbcp-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pip~=21.0
  - python>=3.8,<3.10

  - catalystcoop.pudl>=0.5 # implicitly install almost everything needed

  # Use pip to install the main package for development:
#  - pip:
#    - --editable .
